name: ran_flutter_message
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ran_flutter_core:
    path: '../ran_flutter_core'
  ran_flutter_account:
    path: '../ran_flutter_account'
  # SignalrClient
  signalr_client: ^0.1.6
  flutter_slidable: ^0.5.7
  keyboard_visibility: ^0.5.6
  permission_handler: ^5.0.1
  #https://pub.flutter-io.cn/packages/audio_recorder
  flutter_record_plugin:
    git:
      url: https://github.com/huangruiLearn/flutter_record_plugin.git
      ref: ca5a0f3821616d38842dde4a6588a1ce9ad5673d

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  assets:
    - packages/ran_flutter_message/assets/images/ic_audio.png
    - packages/ran_flutter_message/assets/images/ic_add.png
    - packages/ran_flutter_message/assets/images/ic_emoji.png
    - packages/ran_flutter_message/assets/images/ic_keyboard.png
    - packages/ran_flutter_message/assets/images/ic_ctype_camera.png
    - packages/ran_flutter_message/assets/images/ic_ctype_file.png
    - packages/ran_flutter_message/assets/images/ic_ctype_picture.png
    - packages/ran_flutter_message/assets/images/ic_ctype_video.png
    - packages/ran_flutter_message/assets/images/ic_volume_0.png
    - packages/ran_flutter_message/assets/images/ic_volume_1.png
    - packages/ran_flutter_message/assets/images/ic_volume_2.png
    - packages/ran_flutter_message/assets/images/ic_volume_3.png
    - packages/ran_flutter_message/assets/images/ic_volume_4.png
    - packages/ran_flutter_message/assets/images/ic_volume_5.png
    - packages/ran_flutter_message/assets/images/ic_volume_6.png
    - packages/ran_flutter_message/assets/images/ic_volume_7.png
    - packages/ran_flutter_message/assets/images/ic_volume_8.png
    - packages/ran_flutter_message/assets/images/ic_volume_cancel.png
    - packages/ran_flutter_message/assets/images/ic_volume_wraning.png
    - packages/ran_flutter_message/assets/images/ic_ctype_video_camera.png
